apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  labels:
    app.kubernetes.io/name: metrics-server
    app.kubernetes.io/part-of: infrastructure-stack
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/metrics-server/
    chart: metrics-server
    targetRevision: "3.12.2"  # Latest stable version
    helm:
      releaseName: metrics-server
      values: |
        # Resource allocation
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
        
        # High availability
        replicas: 1
        
        # Pod disruption budget for HA
        podDisruptionBudget:
          enabled: true
          maxUnavailable: 0
        
        # Anti-affinity to spread across nodes
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: metrics-server
                topologyKey: kubernetes.io/hostname
        
        # Deployment strategy
        strategy:
          type: RollingUpdate
          rollingUpdate:
            maxUnavailable: 0
            maxSurge: 1
        
        # Node selector for general workloads (not observability-specific)
        nodeSelector:
          kubernetes.io/os: linux
          Purpose: "general-workloads"
        
        serviceMonitor:
          enabled: false  # Can be enabled if you want to monitor metrics-server itself
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      selfHeal: false
      prune: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PruneProgationPolicy=foreground
      - PruneLast=false
      - Replace=false
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=false
      - RespectIgnoreDifferences=false # whether to ignore differences while syncing or not, used when explicitly use ignoredifference feature
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  # ignoreDifferences:
    # - group: apps
      # kind: Deployment
      # jsonPointers:
        # - /spec/replicas
    # - group: ""
      # kind: Service
      # jsonPointers:
        # - /spec/clusterIP
  revisionHistoryLimit: 3